name: tfdev
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - anyio=4.3.0=pyhd8ed1ab_0
  - argon2-cffi=23.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py312h98912ed_4
  - arrow=1.3.0=pyhd8ed1ab_0
  - asttokens=2.4.1=pyhd8ed1ab_0
  - async-lru=2.0.4=pyhd8ed1ab_0
  - attrs=23.2.0=pyh71513ae_0
  - awkward=2.6.3=pyhd8ed1ab_0
  - awkward-cpp=32=py312h8572e83_0
  - babel=2.14.0=pyhd8ed1ab_0
  - beautifulsoup4=4.12.3=pyha770c72_0
  - blas=1.1=openblas
  - bleach=6.1.0=pyhd8ed1ab_0
  - brotli=1.1.0=hd590300_1
  - brotli-bin=1.1.0=hd590300_1
  - brotli-python=1.1.0=py312h30efb56_1
  - bzip2=1.0.8=hd590300_5
  - ca-certificates=2024.3.11=h06a4308_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - certifi=2024.2.2=py312h06a4308_0
  - cffi=1.16.0=py312hf06ca03_0
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - comm=0.2.2=pyhd8ed1ab_0
  - contourpy=1.2.0=py312hdb19cb5_0
  - cramjam=2.7.0=py312hb7cc22b_0
  - cycler=0.12.1=pyhd8ed1ab_0
  - cython=3.0.10=py312h5eee18b_0
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.8.1=py312h30efb56_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - dill=0.3.7=py312h06a4308_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - exceptiongroup=1.2.0=pyhd8ed1ab_2
  - executing=2.0.1=pyhd8ed1ab_0
  - expat=2.6.2=h6a678d5_0
  - fontconfig=2.14.2=h14ed4e7_0
  - fonttools=4.51.0=py312h98912ed_0
  - fqdn=1.5.1=pyhd8ed1ab_0
  - freetype=2.12.1=h267a509_2
  - fsspec=2024.3.1=py312h06a4308_0
  - glib=2.80.0=hf2295e7_6
  - glib-tools=2.80.0=hde27a5a_6
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - h11=0.14.0=pyhd8ed1ab_0
  - h2=4.1.0=pyhd8ed1ab_0
  - hpack=4.0.0=pyh9f0ad1d_0
  - httpcore=1.0.5=pyhd8ed1ab_0
  - httpx=0.27.0=pyhd8ed1ab_0
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - icu=73.1=h6a678d5_0
  - idna=3.7=pyhd8ed1ab_0
  - iminuit=2.18.0=py312h526ad5a_0
  - importlib-metadata=7.1.0=pyha770c72_0
  - importlib_metadata=7.1.0=hd8ed1ab_0
  - importlib_resources=6.4.0=pyhd8ed1ab_0
  - ipykernel=6.29.3=pyhd33586a_0
  - ipython=8.22.2=pyh707e725_0
  - isoduration=20.11.0=pyhd8ed1ab_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.3=pyhd8ed1ab_0
  - jpeg=9e=h0b41bf4_3
  - json5=0.9.25=pyhd8ed1ab_0
  - jsonpointer=2.4=py312h7900ff3_3
  - jsonschema=4.22.0=pyhd8ed1ab_0
  - jsonschema-specifications=2023.12.1=pyhd8ed1ab_0
  - jsonschema-with-format-nongpl=4.22.0=pyhd8ed1ab_0
  - jupyter-lsp=2.2.5=pyhd8ed1ab_0
  - jupyter_client=7.4.9=pyhd8ed1ab_0
  - jupyter_core=5.7.2=py312h7900ff3_0
  - jupyter_events=0.10.0=pyhd8ed1ab_0
  - jupyter_server=2.14.0=pyhd8ed1ab_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_0
  - jupyterlab=4.1.8=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_1
  - jupyterlab_server=2.27.1=pyhd8ed1ab_0
  - kiwisolver=1.4.4=py312h6a678d5_0
  - krb5=1.20.1=h143b758_1
  - lcms2=2.15=hfd0df8a_0
  - ld_impl_linux-64=2.40=h55db66e_0
  - lerc=3.0=h9c3ff4c_0
  - libbrotlicommon=1.1.0=hd590300_1
  - libbrotlidec=1.1.0=hd590300_1
  - libbrotlienc=1.1.0=hd590300_1
  - libclang13=14.0.6=default_he11475f_1
  - libcups=2.4.2=h2d74bed_1
  - libdeflate=1.17=h0b41bf4_0
  - libedit=3.1.20230828=h5eee18b_0
  - libexpat=2.6.2=h59595ed_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=13.2.0=h77fa898_6
  - libgfortran-ng=13.2.0=h69a702a_6
  - libgfortran5=13.2.0=h43f5ff8_6
  - libglib=2.80.0=hf2295e7_6
  - libgomp=13.2.0=h77fa898_6
  - libiconv=1.17=hd590300_2
  - libllvm14=14.0.6=hdb19cb5_3
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.27=pthreads_h413a1c8_0
  - libpng=1.6.43=h2797004_0
  - libpq=12.17=hdbd6064_0
  - libsodium=1.0.18=h36c2ea0_1
  - libsqlite=3.45.3=h2797004_0
  - libstdcxx-ng=13.2.0=hc0a3c3a_6
  - libtiff=4.5.1=h6a678d5_0
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.4.0=hd590300_0
  - libxcb=1.16=hd590300_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.0.3=he3ba5ed_0
  - libxml2=2.10.4=hfdd30dd_2
  - libzlib=1.2.13=hd590300_5
  - lz4-c=1.9.3=h9c3ff4c_1
  - markupsafe=2.1.5=py312h98912ed_0
  - matplotlib=3.8.4=py312h7900ff3_0
  - matplotlib-base=3.8.4=py312h526ad5a_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - mistune=3.0.2=pyhd8ed1ab_0
  - multiprocess=0.70.15=py312h06a4308_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - mysql=5.7.20=hf484d3e_1001
  - nbclient=0.10.0=pyhd8ed1ab_0
  - nbconvert-core=7.16.4=pyhd8ed1ab_0
  - nbformat=5.10.4=pyhd8ed1ab_0
  - ncurses=6.4.20240210=h59595ed_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - notebook=7.1.3=pyhd8ed1ab_0
  - notebook-shim=0.2.4=pyhd8ed1ab_0
  - numpy=1.26.4=py312h2809609_0
  - numpy-base=1.26.4=py312he1a6c75_0
  - openblas=0.3.27=pthreads_h7a3da1a_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=3.3.0=hd590300_0
  - overrides=7.7.0=pyhd8ed1ab_0
  - packaging=24.0=pyhd8ed1ab_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.4=pyhd8ed1ab_0
  - pcre2=10.43=hcad00b1_0
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pillow=10.3.0=py312h5eee18b_0
  - pip=24.0=pyhd8ed1ab_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_1
  - platformdirs=4.2.1=pyhd8ed1ab_0
  - ply=3.11=pyhd8ed1ab_2
  - prometheus_client=0.20.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.42=pyha770c72_0
  - psutil=5.9.8=py312h98912ed_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pybind11-abi=5=hd3eb1b0_0
  - pycparser=2.22=pyhd8ed1ab_0
  - pygments=2.17.2=pyhd8ed1ab_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyqt=5.15.10=py312h6a678d5_0
  - pyqt5-sip=12.13.0=py312h5eee18b_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.12.3=hab00c5b_0_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-fastjsonschema=2.19.1=pyhd8ed1ab_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-xxhash=2.0.2=py312h5eee18b_1
  - python_abi=3.12=4_cp312
  - pytz=2024.1=pyhd8ed1ab_0
  - pyyaml=6.0.1=py312h98912ed_1
  - pyzmq=24.0.1=py312h5eee18b_0
  - qt-main=5.15.2=h53bd1ea_10
  - readline=8.2=h8228510_1
  - referencing=0.35.1=pyhd8ed1ab_0
  - requests=2.31.0=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_0
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rpds-py=0.18.0=py312h4b3b743_0
  - scipy=1.13.0=py312h2809609_0
  - send2trash=1.8.3=pyh0d859eb_0
  - setuptools=69.5.1=pyhd8ed1ab_0
  - sip=6.7.12=py312h6a678d5_0
  - six=1.16.0=pyh6c4a22f_0
  - sniffio=1.3.1=pyhd8ed1ab_0
  - soupsieve=2.5=pyhd8ed1ab_1
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - terminado=0.18.1=pyh0d859eb_0
  - tinycss2=1.3.0=pyhd8ed1ab_0
  - tk=8.6.13=noxft_h4845f30_101
  - tomli=2.0.1=pyhd8ed1ab_0
  - tornado=6.4=py312h98912ed_0
  - traitlets=5.14.3=pyhd8ed1ab_0
  - types-python-dateutil=2.9.0.20240316=pyhd8ed1ab_0
  - typing-extensions=4.11.0=hd8ed1ab_0
  - typing_extensions=4.11.0=pyha770c72_0
  - typing_utils=0.1.0=pyhd8ed1ab_0
  - tzdata=2024a=h0c530f3_0
  - uproot=5.3.3=ha770c72_0
  - uproot-base=5.3.3=pyhd8ed1ab_0
  - uri-template=1.3.0=pyhd8ed1ab_0
  - urllib3=2.2.1=pyhd8ed1ab_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - webcolors=1.13=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_2
  - websocket-client=1.8.0=pyhd8ed1ab_0
  - wheel=0.43.0=pyhd8ed1ab_1
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xxhash=0.8.0=h7f8727e_3
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7f98852_2
  - zeromq=4.3.5=h59595ed_1
  - zipp=3.17.0=pyhd8ed1ab_0
  - zlib=1.2.13=hd590300_5
  - zstd=1.5.2=h8a70e8d_1
  - pip:
      - absl-py==2.1.0
      - astunparse==1.6.3
      - cloudpickle==3.0.0
      - dm-tree==0.1.8
      - flatbuffers==24.3.25
      - gast==0.5.4
      - google-pasta==0.2.0
      - grpcio==1.63.0
      - h5py==3.11.0
      - keras==3.3.3
      - libclang==18.1.1
      - markdown==3.6
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - ml-dtypes==0.3.2
      - namex==0.0.8
      - nvidia-cublas-cu12==12.3.4.1
      - nvidia-cuda-cupti-cu12==12.3.101
      - nvidia-cuda-nvcc-cu12==12.3.107
      - nvidia-cuda-nvrtc-cu12==12.3.107
      - nvidia-cuda-runtime-cu12==12.3.101
      - nvidia-cudnn-cu12==8.9.7.29
      - nvidia-cufft-cu12==11.0.12.1
      - nvidia-curand-cu12==10.3.4.107
      - nvidia-cusolver-cu12==11.5.4.101
      - nvidia-cusparse-cu12==12.2.0.103
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.3.101
      - opt-einsum==3.3.0
      - optree==0.11.0
      - protobuf==4.25.3
      - rich==13.7.1
      - tensorboard==2.16.2
      - tensorboard-data-server==0.7.2
      - tensorflow==2.16.1
      - tensorflow-probability==0.24.0
      - termcolor==2.4.0
      - tf-keras==2.16.0
      - werkzeug==3.0.2
      - wrapt==1.16.0
